### ISSUE TITLE
ECK rollout on Mac and usage of ECK support diagnostics results in error

### ISSUE THREAD

**Issue by 111andre111** [elastic/eck-support-diagnostics#1]
I met some errors using the ECK deployment on a Mac environment:
1. `top -n1 -b` which is the so called batch mode under Gnutools and for the BSD verison is not working but the logging mode is the solution `top -n1 -l1` only once or `top -n1 -l0` infinite time.
2. I needed to execute ECK diagnostics with sudo... because otherwise it will not create the `/docker` tmp directories. Maybe a better approach would be as well to temporariy create it under the /tmp directory...
with e.g. `diag_folder=/tmp/eckdiagnostics ./eck-diagnostics.sh -s -d -k -t 2h` everything was working
3. sar command not working, maybe ksar can be an alternative, but is not installed normally either
4. `netstat -anp` command not working  --->  -p Parameter is not existing, but can be replaced by `lsof -i -P | grep -i "listen"`
5. `netstat -ntulpn` command not working  ---> again -p parameter, see 4.  - additionally -t parameter not existing, but can be replaced by -ptcp so it should be `netstat -nuln -ptcp`
6. `route -n` command not working, equivalent is `netstat -nr`
7. iptables -L not working -> pfctl may be the equivalent tool
8. docker folder not packed into tar.gz if diag_folder used like under 2.
  --> issue is docker_folder has wrong place, it is declared before diag_folder is described, if you place here:
```
assign_output_paths

docker_folder=$diag_folder/docker
```
Then it's working.

9. `cat /etc/*-release` not working. Equivalents are `system_profiler SPSoftwareDataType` or `sw_vers -productVersion`

**Comment by eedugon** [comment]
I think we should clarify from where the tool is expected to be executed and the flags, because:
ECK runs in Kubernetes, so the `-s` and `-d` flags would only have sense if the tool is executed from inside a Kubernetes worker (running kubelet).

What flags is the tool running by default? In my view it should run only collects and checks based on `kubectl`, as most probably the tool will be used from a client more than a real kubernetes node, so system and docker checks would be unnecessary.
cc: @PhaedrusTheGreek , let me know your thoughts.

**Comment by PhaedrusTheGreek** [comment]
`-d -s` was not meant to run on macOS.   However with ECK this might be common since we can expect `kubectl` to sometimes be running locally.   I will disable those flags if OS is identified to be Cygwin or Darwin.

**Comment by eedugon** [comment]
But even if the tool is run from a linux laptop, most probably is not a
kubernetes node, usually when you have a cluster you operate it from out of
the cluster, via the API (kubectl). I would say that 95% of times we should
expect the diag to be run in that "remote" way. Then getting OS information
from a computer that is technically irrelevant could create confusion (in
my view).
I also like the idea of running it in a locally in a kubernetes worker, but
maybe we should specify a clear flag for it, and describe it in the doc.
If you want help with any of this let me know.

**Comment by PhaedrusTheGreek** [comment]
I propose that a `--remote` flag complicates rather than simplifies in this case because the default behaviour is *to not* run `-d -s`.  

For now I have made the following precautions:

- don't allow `-k` unless `kubectl` command is present
- don't allow `-d` or `-s` unless `docker` command is present
- don't allow `-d` or `-s` if uname shows `CYGWIN` or `Darwin`
- don't allow `-d` or `-s` unless `kubelet` process is running
